services:
  sql_feedback:
    build: sql_feedback
    environment:
      OPENAI_API_KEY: 1234
      BASE_URL: https://llm.example.org/v1

  persistence_proxy:
    build: persistence_proxy
    environment:
      DATABASE_URL: postgresql://postgres:1234@db
      UPSTREAM_URL: http://sql_feedback:80/api/v1/analyse
    ports:
    - 8080:8080
    depends_on:
    - db
    - sql_feedback

  db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_PASSWORD: 1234 # CHANGE FOR PROD
    volumes:
    - ./db:/bitnami/postgresql
