services:
  sql_feedback:
    build: sql_feedback
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      BASE_URL: ${BASE_URL}

  persistence_proxy:
    build: persistence_proxy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      UPSTREAM_URL: ${UPSTREAM_URL}
    ports:
      - ${PERSISTENCE_PROXY_PORT}:8080
    depends_on:
      - db
      - sql_feedback

  db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD} # CHANGE FOR PROD
    volumes:
      - ./db:/bitnami/postgresql
